name: Run Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: MunifTanjim/setup-neovim-action@v1
      - name: Run tests
        run: make test
